# Generated by Django 4.0.6 on 2022-07-17 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_post_disliked_users_alter_post_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='disliked_users',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
