# Generated by Django 4.0.6 on 2022-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_userprofile_following_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interested_tags',
            field=models.ManyToManyField(blank=True, to='base.tag'),
        ),
    ]
